### ISSUE TITLE
Archlinuxcn 仓库与 Manjaro 的 stable 分支可能会产生冲突

### ISSUE THREAD

**Issue by SamLukeYes** [Firestar-Reimu/Manjaro-KDE-Installation#1]
archlinuxcn 的软件包是在 Arch 的环境下打包的，Arch 的更新通常比 Manjaro 的 stable 分支要领先一两个星期。有时 Arch 的某些lib 更新之后，相应的软件包需要重新打包，才能调用较新版本的 lib，archlinuxcn 在此时也会跟进 Arch 的更新进行重新打包；而此时 Manjaro 的 stable 分支通常还没有收到 lib 的更新，如果更新了 archlinuxcn 上的这个刚刚重新打包的软件包，就会导致这个包不可用。

我在几个月前踩过一次这个坑，涉及的软件包是 archlinuxcn 的 aria2-fast 和 Manjaro 官方仓库的 nettle。从那以后，我就一直使用 unstable 分支，这个分支通常比 Arch 更新滞后不超过一天（官方说法是不超过三天）。虽然官方警告说使用 unstable 分支可能会导致系统损坏，但实际上现在上游 Arch 并不经常出问题，因此 Manjaro 的 unstable 分支也不会有太多问题，即使出了问题也基本上是和 Arch 一样的问题。

如果执意用 stable 分支，就不建议用 archlinuxcn 源。如果不需要 archlinuxcn 特有的软件包，或者 archlinuxcn 上有但通过 AUR 难以构建的软件包，就完全可以不用 archlinuxcn。

切换分支的方法：https://wiki.manjaro.org/index.php?title=Switching_Branches

**Comment by Firestar-Reimu** [comment]
谢谢！那么我其实可以考虑用unstable分支？

**Comment by SamLukeYes** [comment]
> 谢谢！那么我其实可以考虑用unstable分支？

是的。尤其是用 KDE，真正的 bleeding edge 并不是切换到 unstable 分支就能碰到的。

BTW，用 unstable 分支的话建议多关注这里的公告：https://forum.manjaro.org/c/announcements/unstable-updates/
