### ISSUE TITLE
为什么没有/boot分区？

### ISSUE THREAD

**Issue by Firestar-Reimu** [Firestar-Reimu/Manjaro-KDE-Installation#3]
为什么没有`/boot`分区？

**Comment by SamLukeYes** [comment]
如果是用 grub，没必要单独分个 /boot，把 esp 挂载到 /boot/efi 就好了。如果用 systemd-boot，就直接把 esp 挂载为 /boot。分区太多其实不便于管理，少分区能够更灵活地分配空间。如果你的个人文件都有备份，甚至连 /home 都不用分，只分个 / 就好了。

**Comment by Firestar-Reimu** [comment]
谢谢，我用的是grub，看来我甚至可以只需要挂 / 和 /boot-efi
