### ISSUE TITLE
下载了Intel P-state and CPUFreq Manager Widget，怎么样是关闭了turbo

### ISSUE THREAD

**Issue by Firestar-Reimu** [Firestar-Reimu/Manjaro-KDE-Installation#5]
![Screenshot_20200915_164525](https://user-images.githubusercontent.com/65082432/93188110-29a1f100-f773-11ea-9363-a36ea0850cd9.png)
这样是开启
![Screenshot_20200915_164622](https://user-images.githubusercontent.com/65082432/93188133-332b5900-f773-11ea-82f8-89d11cf5356a.png)
这样是关闭

是这样吗？

PS：如何让它保存设置而不是重启之后就没了

**Comment by SamLukeYes** [comment]
我觉得这可能是你的主题的锅……要不你看看其他 Qt 软件的勾选框是什么样的？或者，可以在有一定负载的情况下观察实时频率，开了 turbo 的话很容易到 2 GHz 以上。
这个小工具似乎并没有保存设置的功能。如果需要开机默认关闭 turbo 的话，可以考虑自己写一个 systemd 服务。

**Comment by Firestar-Reimu** [comment]
可以看我最新的更新，我已经用别的方法解决了

**Comment by SamLukeYes** [comment]
> 可以看我最新的更新，我已经用别的方法解决了

linux-surface 的作者不推荐使用 TLP

> Using TLP can cause slowdowns, laggy performance, and occasional hangs if not configured properly! You have been warned.
https://github.com/linux-surface/linux-surface#notes

当然，如果你觉得你驾驭得好 TLP，应该也没什么问题
