### ISSUE TITLE
凡是可以从软件仓库获取或从 AUR 正确构建的软件包，不建议用 debtap

### ISSUE THREAD

**Issue by SamLukeYes** [Firestar-Reimu/Manjaro-KDE-Installation#6]
根据 debtap 的 [FAQ](https://github.com/helixarch/debtap#faq)，debtap 是个脏办法，它的原作者甚至鼓励你在能自己写 PKGBUILD 的时候就别用 debtap

**Comment by Firestar-Reimu** [comment]
那个Code-OSS的默认图标太丑了，如果能改成那个蝴蝶结形状的话（见下），我会用它的。
![Screenshot_20200921_213441](https://user-images.githubusercontent.com/65082432/93773113-44cc9f00-fc52-11ea-92b1-40ebdf338a9e.png)

**Comment by SamLukeYes** [comment]
> 那个Code-OSS的默认图标太丑了，如果能改成那个蝴蝶结形状的话（见下），我会用它的。
> ![Screenshot_20200921_213441](https://user-images.githubusercontent.com/65082432/93773113-44cc9f00-fc52-11ea-92b1-40ebdf338a9e.png)

我用的是 [archlinuxcn] 的 `visual-studio-code-bin`，AUR 上也有这个包，就是从官方的 .deb 包转制的，不需要自己再用 debtap。

**Comment by Firestar-Reimu** [comment]
好的谢谢

**Comment by SamLukeYes** [comment]
Fixed by 4cd8ec7.
