### ISSUE TITLE
建议加入“手动选择让此 Surface 从 U 盘启动”的内容

### ISSUE THREAD

**Issue by wr786** [Firestar-Reimu/Manjaro-KDE-Installation#8]
> https://support.microsoft.com/zh-cn/help/4023511/surface-boot-surface-from-a-usb-device

`设置 --> 恢复 --> 立即重新启动 --> USB Storage`在我的这台`Surface Pro 6`上并不能成功从启动盘启动。

因此建议在“制作启动盘”与“安装 Manjaro”之中插入这一项：
```
如何从 USB 启动。 

关闭 Surface。
将可启动 U 盘插入 Surface 上的 USB 端口。
长按 Surface 上的调低音量按钮。 执行此操作时，请按下并释放 "电源" 按钮。
屏幕上会显示 Microsoft 或 Surface 徽标。 继续按住调低音量按钮。 释放按钮后，徽标下方将显示旋转圆点。
按照屏幕说明从 U 盘启动。
```

**Comment by Firestar-Reimu** [comment]
你用的是rufus还是ventoy做启动盘？我这个方法只适用于rufus，ventoy我没试过。

**Comment by wr786** [comment]
是Ventoy的，毕竟你这写的就是ventoy（

**Comment by Firestar-Reimu** [comment]
啊，这个是SamLukeYes改的
https://github.com/1900011604/Manjaro-KDE-Installation-on-Surface-Pro-6/pull/2/commits/41700eb0b6bfaeadc0a5af4e9d60207dd9c09b28

我不是很会用ventoy所以我还是改成rufus吧？没有实操过我也不好说。

https://support.microsoft.com/zh-cn/help/4023511/surface-boot-surface-from-a-usb-device

也就是说这里面的第二条你用不了？我下午改一下。

PS：请确认是否关闭了secure boot

**Comment by SamLukeYes** [comment]
此处是设置从 U 盘启动的过程，应该和用 ventoy 还是 rufus 无关

**Comment by wr786** [comment]
> 啊，这个是SamLukeYes改的
> [41700eb](https://github.com/1900011604/Manjaro-KDE-Installation-on-Surface-Pro-6/commit/41700eb0b6bfaeadc0a5af4e9d60207dd9c09b28)
> 
> 我不是很会用ventoy所以我还是改成rufus吧？没有实操过我也不好说。
> 
> https://support.microsoft.com/zh-cn/help/4023511/surface-boot-surface-from-a-usb-device
> 
> 也就是说这里面的第二条你用不了？我下午改一下。

如果“第二条“指的是`将 Surface 配置为从 U 盘启动`，那我确实也用不了。事实上，我无法*拖动*“USB 存储”到列表顶部。

**Comment by wr786** [comment]
备注：
- 快速启动已关闭
- BitLocker已关闭
- Secure Boot选项是`None`，即disabled，

**Comment by Firestar-Reimu** [comment]
可以用Hasleo UEFI编辑启动项哦

**Comment by Firestar-Reimu** [comment]
![IMG_20201017_140405](https://user-images.githubusercontent.com/65082432/96329661-db3d8600-1081-11eb-8fb5-e6e8323b866b.jpg)

![IMG_20201017_140429](https://user-images.githubusercontent.com/65082432/96329665-e690b180-1081-11eb-9557-88e84d24aa73.jpg)

![IMG_20201017_140443](https://user-images.githubusercontent.com/65082432/96329667-edb7bf80-1081-11eb-8566-6f059b3228df.jpg)

**Comment by Firestar-Reimu** [comment]
已经加入“手动选择让此 Surface 从 U 盘启动”的内容

**Comment by wr786** [comment]
> 可以用Hasleo UEFI编辑启动项哦

好的，我晚些再试试
